controller: fix updating of volume cache
Commit 935885b3430c107852ca23f57ddd550b09532bed added usage of the
informer cache to reduce the number of requests to the API server. But
the code which was meant to add and remove PVs from the cache did so
with the PV name, which didn't work and always caused error log
entries like this:

E1008 09:41:32.581837       1 controller.go:1443] couldn't create key for object pvc-ca12922f-a4e0-426b-9704-244f00227c05: object has no meta: object does not implement the Object interfaces
...
E1008 09:43:18.441727       1 controller.go:1521] couldn't create key for object pvc-17e4c2d0-114d-4260-b587-c39a86c8dfe5: object has no meta: object does not implement the Object interfaces